<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">


        <style>
            @page{
                margin: 0;
            }
            *,::after,::before{box-sizing:border-box;user-select: none !important;pointer-events: none;}
            body{margin:0;font-family:"Source Sans Pro",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:1rem;font-weight:400;line-height:1.5;color:#212529;text-align:left;background-color:#fff;}
            table{border-collapse:collapse;}
            th{text-align:inherit;text-align:-webkit-match-parent;}
            .table{width:100%;margin-bottom:1rem;color:#212529;background-color:transparent;}
            .table td,.table th{padding:.75rem;vertical-align:top;border-top:1px solid #dee2e6;}
            .table thead th{vertical-align:bottom;border-bottom:2px solid #dee2e6;}
            .table-borderless td,.table-borderless th,.table-borderless thead th{border:0;}
            .table-hover tbody tr:hover{color:#212529;background-color:rgba(0,0,0,.075);}
            .badge{display:inline-block;padding:.25em .4em;font-size:75%;font-weight:700;line-height:1;text-align:center;white-space:nowrap;vertical-align:baseline;border-radius:.25rem;transition:color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;}
            @media (prefers-reduced-motion:reduce){
            .badge{transition:none;}
            }
            .badge:empty{display:none;}
            .badge-success{color:#fff;background-color:#28a745;}
            .border-bottom{border-bottom:1px solid #dee2e6!important;}
            .text-center{text-align:center!important;}
            @media print{
            *,::after,::before{text-shadow:none!important;box-shadow:none!important;}
            thead{display:table-header-group;}
            tr{page-break-inside:avoid;}
            body{min-width:992px!important;}
            .badge{border:1px solid #000;}
            .table{border-collapse:collapse!important;}
            .table td,.table th{background-color:#fff!important;}
            }
            body{min-height:100%;}
            .table:not(.table-dark){color:inherit;}
            table td,table th{vertical-align:middle!important;}
            .text-success {color: #28a745!important;}
            .text-danger {color: #dc3545!important;}
            .border{border:1px dashed #d1d1d1!important;}



        </style>

   </head>
   <body style="padding: 45px;">
    <script type="text/php">
        if ( isset($pdf) ) {
            $page_counter = "1 of 1";
            $pdf->page_script('
                if ($PAGE_COUNT > 1) {
                    $font = $fontMetrics->get_font("Arial, Helvetica, sans-serif", "normal");
                    $size = 9;
                    $pageText = $PAGE_NUM . " of " . $PAGE_COUNT;
                    $y = 112;
                    $x = 149;
                    $pdf->text($x, $y, $pageText, $font, $size);
                }
            ');
        }
    </script>


    {{-- <div id="watermark" style="user-select: none !important;text-align:justify;position: fixed;color:rgb(243, 243, 243);top:0;left:0;width:100%;height:100vh;z-index:-1;font-size:10px;">
        @php $watermark = 1500 @endphp
        @while ($watermark > 1)
            &nbsp; Laravel Project
            @php $watermark-- @endphp
        @endwhile
    </div> --}}

    <table class="table table-borderless table-hover" style="font-size: 12.5px !important;" >
        <thead class="border" class="table-info">
            <tr>
                <th>
                    Site Name:
                </th>
                <td colspan="6">
                    @config('app.name')
                </td>
            </tr>
            <tr>
                <th>
                    Page Name:
                </th>
                <td colspan="6">
                    Users List
                </td>
            </tr>
            <tr>
                <th>
                    Page Number:
                </th>
                <td colspan="6">

                </td>
            </tr>
            <tr>
                <th>
                    Generated By
                </th>
                <td colspan="6">
                   {{auth()->user()->name}} ({{auth()->user()->email}})
                </td>
            </tr>
            <tr>
                <th>
                    Generated At
                </th>
                <td colspan="6">
                   {{ now()->format('F d, Y h:i:s A') }}
                </td>
            </tr>
        </thead>
        <thead class="border-bottom">
            <tr>
                <th colspan="7">

                </th>
            </tr>
            <tr>
                <th class="text-center">ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th class="text-center">Approved</th>
                <th>Date of Registration</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($users as $user)
                <tr>
                    <td class="text-center">{{ str_pad($user->id, 4, 0, STR_PAD_LEFT)}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <th>
                        {{$user->role->name}}
                    </th>
                    <th class="text-center">
                        @if($user->approved)
                            YES
                        @else
                            NO
                        @endif
                    </th>
                    <td>
                        {{$user->created_at->format('F d, Y h:i A')}}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="100%" class="text-center text-muted small">
                        No Users Found
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>


   </body>
</html>


